using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable UnusedMember.Local
namespace BlogEngine.PublishedLanguage
{
    #region Generated by Lokad Code DSL
    
        
    
    [DataContract(Namespace = "Fjord/BlogEngine")]
    public partial class StartBlog : Command, IBlogCommand
    {
        [DataMember(Order = 1)] public BlogId Id { get; private set; }
        [DataMember(Order = 2)] public string Name { get; private set; }
        
        StartBlog () {}
        public StartBlog (BlogId id, string name)
        {
            Id = id;
            Name = name;
        }
        
        public override string ToString()
        {
            return string.Format(@"Start blog {0}", Name);
        }
    }
    
        
    
    [DataContract(Namespace = "Fjord/BlogEngine")]
    public partial class BlogStarted : Event, IBlogEvent
    {
        [DataMember(Order = 1)] public BlogId Id { get; private set; }
        [DataMember(Order = 2)] public string Name { get; private set; }
        [DataMember(Order = 3)] public DateTime TimeUtc { get; private set; }
        
        BlogStarted () {}
        public BlogStarted (BlogId id, string name, DateTime timeUtc)
        {
            Id = id;
            Name = name;
            TimeUtc = timeUtc;
        }
        
        public override string ToString()
        {
            return string.Format(@"Blog {0} started at {1}", Name, TimeUtc);
        }
    }
    
        
    
    [DataContract(Namespace = "Fjord/BlogEngine")]
    public partial class PostStory : Command, IBlogCommand
    {
        [DataMember(Order = 1)] public BlogId Id { get; private set; }
        [DataMember(Order = 2)] public string Author { get; private set; }
        [DataMember(Order = 3)] public string Title { get; private set; }
        [DataMember(Order = 4)] public string Body { get; private set; }
        
        PostStory () {}
        public PostStory (BlogId id, string author, string title, string body)
        {
            Id = id;
            Author = author;
            Title = title;
            Body = body;
        }
        
        public override string ToString()
        {
            return string.Format(@"Post story {1} by {0}", Author, Title);
        }
    }
    
        
    
    [DataContract(Namespace = "Fjord/BlogEngine")]
    public partial class StoryPosted : Event, IBlogEvent
    {
        [DataMember(Order = 1)] public BlogId Id { get; private set; }
        [DataMember(Order = 2)] public string Author { get; private set; }
        [DataMember(Order = 3)] public DateTime TimeUtc { get; private set; }
        [DataMember(Order = 4)] public string Title { get; private set; }
        [DataMember(Order = 5)] public string Body { get; private set; }
        
        StoryPosted () {}
        public StoryPosted (BlogId id, string author, DateTime timeUtc, string title, string body)
        {
            Id = id;
            Author = author;
            TimeUtc = timeUtc;
            Title = title;
            Body = body;
        }
        
        public override string ToString()
        {
            return string.Format(@"Story {2} posted at {1} by {0}", Author, TimeUtc, Title);
        }
    }
    
    public interface IBlogApplicationService
    {
        void When(StartBlog c);
        void When(PostStory c);
    }
    
    public interface IBlogState
    {
        void When(BlogStarted e);
        void When(StoryPosted e);
    }
    #endregion
}
