using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable UnusedMember.Local
namespace BlogEngine.PublishedLanguage
{
    #region Generated by Lokad Code DSL
    
        
    
    [DataContract(Namespace = "Fjord/BlogEngine")]
    public partial class StartBlog : Command, IBlogCommand
    {
        [DataMember(Order = 1)] public BlogId Id { get; private set; }
        [DataMember(Order = 2)] public string Name { get; private set; }
        [DataMember(Order = 3)] public DateTime TimeUtc { get; private set; }
        
        StartBlog () {}
        public StartBlog (BlogId id, string name, DateTime timeUtc)
        {
            Id = id;
            Name = name;
            TimeUtc = timeUtc;
        }
        
        public override string ToString()
        {
            return string.Format(@"Start blog - {0} at {1}", Name, TimeUtc);
        }
    }
    
        
    
    [DataContract(Namespace = "Fjord/BlogEngine")]
    public partial class BlogStarted : Event, IBlogEvent
    {
        [DataMember(Order = 1)] public BlogId Id { get; private set; }
        [DataMember(Order = 2)] public string Name { get; private set; }
        [DataMember(Order = 3)] public DateTime TimeUtc { get; private set; }
        
        BlogStarted () {}
        public BlogStarted (BlogId id, string name, DateTime timeUtc)
        {
            Id = id;
            Name = name;
            TimeUtc = timeUtc;
        }
        
        public override string ToString()
        {
            return string.Format(@"Blog {0} started at {1}", Name, TimeUtc);
        }
    }
    
    public interface IBlogApplicationService
    {
        void When(StartBlog c);
    }
    
    public interface IBlogState
    {
        void When(BlogStarted e);
    }
    #endregion
}
